[Master] Made profile (first craft)
jarviscanada/jarvis_data_eng_AliSaboohi pull request #2
Opened 2021-12-22 19:48 UTC by alisbi

2022-01-03 18:21 UTC, trevor-jrvs requested changes
Introduction is too short: I will send you some sample profiles on slack. Please remove any unstarted projects, and make sure there is no remaining Lorem ipsum text.

2022-01-11 15:51 UTC, jarviscanada approved these changes

2022-01-11 15:51 UTC, jarviscanada commented on README.md
> +Hi, I'm a recent graduate from Ryerson university with a bachelor's degree in Computer Science. During my four years at Ryerson my main focus was on backend development, machine learning and computer
I'm a recent graduate from Ryerson University with a bachelor's degree in Computer Science. During my four years at Ryerson, my main focus was on backend development, machine learning and computer vision, where I worked on many projects such as Face Detection application using HOG features, Handwrite Recognition application and created a few websites. Currently, I am a Software and Data Engineer at Jarvis, where I am trained to master the tools and frameworks necessary for a professional work environment such as Git, Docker, Java, Spring boot, RDBMS, Maven etc. In addition to this, I have a passion for the insights data can provide. My experiences taught me how to come up with creative solutions to real-world problems, and I am looking forward to bringing my experiences and skills to your team.

2022-01-11 15:51 UTC, jarviscanada commented on README.md
> +**Competent:** Docker, Maven, REST API, JDBC, Spring Boot
Spring Boot, REST API, JDBC, Docker, Maven

2022-01-11 15:51 UTC, jarviscanada commented on README.md
> +**Cluster Monitor** [[GitHub](https://github.com/jarviscanada/jarvis_data_eng_AliSaboohi/tree/master/linux_sql)]: The Objective of this project was to design an MVP in order to gather hardware specif
Developed a hardware resource monitoring program that collects CPU, RAM, blahahaha in rea-time using Bash scripts, PostgreSQL, Linux, etc. Data is persisted into a PostgreSQL database instance provisioned using a Docker container. Wrote SQL queries to analyze blah blah for blah blah..

2022-01-11 15:51 UTC, jarviscanada commented on README.md
> +  - Grep App:
remove

2022-01-11 15:51 UTC, jarviscanada commented on README.md
> +**Clothing Store Web Application**: Designed and Developed Online clothing Web site with Online Shopping facility. using Java and Spring Boot for backend and React Js for Frontend. Frontend developed
Designed and Developed an online clothing e-commerce website. The frontend was developed using JavaScript ES6 Version, Vanilla JavaScript, Babel, React-Dom-route, Redux, HTML and CSS. The backend was developed using Spring Core for dependency Injection and AOP, Spring MVC to build Rest Endpoints and JSON. Implemented Data Entity Classes using Hibernate, Spring Data JPA, JPA QL to manage and store data in MySQL Database.

2022-01-11 15:51 UTC, jarviscanada commented on README.md
> +**Software Developer, Jarvis (2020-present)**: Collaborated with a Software and Data engineering team in an Agile enviroment in order to work on various projects using technologies, tools and framewo
Collaborated with a Software and Data engineering team in an Agile environment to work on various projects using technologies, tools and frameworks such as git, Maven, Java, PostgresSQL, IntelliJ, Docker, etc. Organized daily scrum meetings as well as bi-weekly sprint retrospectives. Studied and practiced new technologies and better ways to develop better solutions to real-world problems.

2022-01-11 15:51 UTC, jarviscanada commented on README.md
> +**Ryerson university (2018-2021)**, Bachelor of Computer Science, Science and Engineering
Edward Wang  Nov 2nd, 2021 at 1:35 PM
https://github.com/jarviscanada/jarvis_data_eng_NarimanAlimuradov
https://github.com/jarviscanada/jarvis_data_eng_JasmeetBrar
https://github.com/jarviscanada/jarvis_data_eng_AlexKirilenko
https://github.com/jarviscanada/jarvis_data_eng_FatimaAnwer
white_check_mark
eyes
raised_hands





Direct Message

Edward Wang  Nov 2nd, 2021 at 1:34 PM
https://github.com/jarviscanada/jarvis_data_eng_BrandonDicicco
https://github.com/jarviscanada/jarvis_data_eng_JohnCao
https://github.com/jarviscanada/jarvis_data_eng_TomasRotbauer
https://github.com/jarviscanada/jarvis_data_eng_TinaLee

2022-01-11 16:26 UTC, jarviscanada approved these changes

2022-01-12 14:36 UTC, merged